"""update

Revision ID: 1a57072bc12f
Revises: b3445580037c
Create Date: 2025-11-15 20:32:09.030861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a57072bc12f'
down_revision: Union[str, Sequence[str], None] = 'b3445580037c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipping_costs', 'cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=4, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipping_costs', 'cost',
               existing_type=sa.Numeric(precision=4, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
