"""add users table

Revision ID: 5df0c7a3f680
Revises: 89a682145a03
Create Date: 2025-11-08 19:49:38.324201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df0c7a3f680'
down_revision: Union[str, Sequence[str], None] = '89a682145a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_session', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_package_associations')
    op.add_column('packages', sa.Column('user_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'user_id')
    op.create_table('user_package_associations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('package_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('user_package_associations_package_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_package_associations_pkey'))
    )
    op.drop_table('user_session')
    # ### end Alembic commands ###
