"""add unique type package name

Revision ID: 89a682145a03
Revises: 4d9997ce5889
Create Date: 2025-11-06 23:23:17.726982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a682145a03'
down_revision: Union[str, Sequence[str], None] = '4d9997ce5889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'type_packages', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'type_packages', type_='unique')
    # ### end Alembic commands ###
