"""delete table ShippingCost

Revision ID: 8ce93becfb33
Revises: 1a57072bc12f
Create Date: 2025-11-15 23:29:43.190092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce93becfb33'
down_revision: Union[str, Sequence[str], None] = '1a57072bc12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipping_costs')
    op.add_column('packages', sa.Column('package_cost', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('packages', sa.Column('delivery_cost', sa.Numeric(precision=5, scale=2), nullable=True))
    op.drop_column('packages', 'cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('cost', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.drop_column('packages', 'delivery_cost')
    op.drop_column('packages', 'package_cost')
    op.create_table('shipping_costs',
    sa.Column('package_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cost', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('shipping_costs_package_id_fkey')),
    sa.PrimaryKeyConstraint('package_id', name=op.f('shipping_costs_pkey'))
    )
    # ### end Alembic commands ###
