"""upgrade decimal max digits

Revision ID: b3445580037c
Revises: 526151cee1a2
Create Date: 2025-11-11 22:46:04.250187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3445580037c'
down_revision: Union[str, Sequence[str], None] = '526151cee1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('packages', 'cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('packages', 'weight',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('packages', 'weight',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.NUMERIC(precision=10, scale=3),
               existing_nullable=False)
    op.alter_column('packages', 'cost',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
