services:
    delivery-service-app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - HTTP_PROXY=${HTTP_PROXY}
                - HTTPS_PROXY=${HTTPS_PROXY}
        
        ports:
            - "${API_PORT}:${API_PORT}"
        depends_on:
            - database
            - redis
        command:
            sh -c "/app/.venv/bin/python main.py run-api"

        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:${API_PORT}/health/"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    scheduler:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - HTTP_PROXY=${HTTP_PROXY}
                - HTTPS_PROXY=${HTTPS_PROXY}
        
        depends_on:
            - database
            - redis
        command:
            sh -c "/app/.venv/bin/python main.py run-scheduler"
        healthcheck:
            test: ["CMD-SHELL", "ps aux | grep -q '[p]ython.*scheduler' || exit 1"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 20s


    database:
        image: postgres:17.4-alpine
        ports:
            - "5434:${DB_PORT}"
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}

        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
    
    redis:
        image: redis:7.2.5-alpine
        hostname: redis
        ports:
            - "6379:${REDIS_PORT}"
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s


volumes:
    postgres_data:
